SELECT
    TARJETA,
    CUENTA,
    LEFT(REPLACE(SUBSTRING(CUENTA, 4, LEN(CUENTA)), '000', ''), 6) AS BINES,
    SUBSTRING(CUENTA, 4, LEN(CUENTA)) AS NUM_CUENTA,
    CASE 
        WHEN BLOQ_OPER = '' THEN ''
        ELSE 'Q'
    END AS BLOQ_OPER,
    CASE
        WHEN Bloq_Cobr = '' THEN ''
        ELSE 'G'
    END AS BLOQUEO_CO
FROM
    IT_CARTERA_SUB
WHERE
    LEFT(REPLACE(SUBSTRING(CUENTA, 4, LEN(CUENTA)), '000', ''), 6) = '481284';


