SELECT
    TARJETA,
    ULTC,
    CUENTA,
    LEFT(REPLACE(SUBSTRING(CUENTA, 4, LEN(CUENTA)), '0', ''), 6) AS BINES,
    SUBSTRING(CUENTA, 4, LEN(CUENTA)) AS NUM_CUENTA,
    CASE 
        WHEN BLOQ_OPER = '' THEN ''
        ELSE 'Q'
    END AS BLOQ_OPER,
    CASE
        WHEN Bloq_Cobr = '' THEN ''
        ELSE 'G'
    END AS BLOQUEO_CO
FROM
    IT_CARTERA_SHASA
--ACTIVACION >= '2023-01-01 00:00:00.000'
---AND ACTIVACION <= '2023-08-25 00:00:00.000'
---LEFT(NO_DE_CUENTA, 6) IN ('403750', '506469');
