SELECT CUENTAREAL, APROBACION, FECHA, ANIO ,MES, SOCIO, PRODUCTO, TRANSACCION, MONTOREAL, TIPOTXN, TIPORETIRO 
FROM(
SELECT NUM_CTA_CTAF AS CUENTA, DAT_ADES_CTAF AS APROBACION, DAT_TRANS_SAQ AS FECHA
, YEAR(FECHA) AS ANIO, MONTH(FECHA) AS MES
, CASE 	WHEN COD_ORG_CTAF IN (310,311,320) THEN 'C&A'
WHEN COD_ORG_CTAF IN (373,353) THEN 'Suburbia'
WHEN COD_ORG_CTAF IN (372,352,362) THEN 'Bodega'
WHEN COD_ORG_CTAF IN (375,355,365) THEN 'Shasa'
WHEN COD_ORG_CTAF IN (374,354) THEN 'GCC'
WHEN COD_ORG_CTAF IN (377,357,367) THEN 'Promoda'
WHEN COD_ORG_CTAF IN (360) AND DAT_ADES_CTAF < '2020-06-01' THEN 'EFECTIVO'
WHEN COD_ORG_CTAF IN (360) AND DAT_ADES_CTAF >= '2020-06-01'  THEN 'GCC'
ELSE 'OTRO' END SOCIO
, CASE 	WHEN COD_ORG_CTAF IN (310,311,373,372,375,374,377) THEN 'PLCC'
WHEN COD_ORG_CTAF IN (320,353,352,355,354,357) THEN 'BK'
WHEN COD_ORG_CTAF IN (340, 341,360,365,367,362) THEN 'PL'
ELSE 'OTRO' END PRODUCTO
, 'D' AS TRANSACCION
, (VAL_TRANS_SAQ - VAL_JUROS_PARC_SAQ) AS MONTO
, CRE.VAL_DADO_ORIG_LKP AS Cre_Vision, CRE.DES_PLANO_CRED_LKP AS Des_Credito
, TRA.VAL_DADO_ORIG_LKP AS TXN_Vision, TRA.DES_TIPO_TRANS_LKP AS Des_Txn
, CASE WHEN (TXN_Vision LIKE '%085' OR TXN_Vision LIKE '%064' OR TXN_Vision LIKE '%075') THEN NULL ELSE Cuenta END AS CuentaReal
, CASE WHEN (TXN_Vision LIKE '%085' OR TXN_Vision LIKE '%064' OR TXN_Vision LIKE '%075') THEN (Monto * -1) ELSE Monto END AS MontoReal
, 'OF' AS TIPOTXN --CASE WHEN ( Des_Credito LIKE '% ATM %' OR Des_Credito LIKE '% PROSA %') THEN 'OF' ELSE 'ON' END AS TIPOTXN
, CASE WHEN DAT_PRI_SAQ_CTAF =  DAT_TRANS_SAQ THEN 'P' ELSE 'R' END TIPORETIRO
FROM CONTA_FINANCIAMENTO_V
INNER JOIN CARTAO_FINANCIAMENTO_V ON ID_CTA_CTAF = ID_CTA_CARF
INNER JOIN  SAQUE_V  ON ID_CAR_SAQ =  ID_CAR_CARF
INNER JOIN PLANO_CREDITO_V CRE ON ID_PLANO_CRED_LKP = ID_PLANO_CRED_SAQ
INNER JOIN TIPO_TRANSACAO_V TRA ON ID_TIPO_TRANS_LKP = ID_TIPO_TRANS_SAQ
INNER JOIN CANAL_V ON  ID_CANA_SAQ = ID_CANA_CAN 
WHERE ( TRA.VAL_DADO_ORIG_LKP LIKE '%085' OR TRA.VAL_DADO_ORIG_LKP LIKE '%064'
OR TRA.VAL_DADO_ORIG_LKP LIKE '%075' OR TRA.VAL_DADO_ORIG_LKP LIKE '%039'
OR TRA.VAL_DADO_ORIG_LKP LIKE '%038' OR TRA.VAL_DADO_ORIG_LKP LIKE '%035'
OR TRA.VAL_DADO_ORIG_LKP LIKE '%051' OR TRA.VAL_DADO_ORIG_LKP LIKE '%054')
AND ( CRE.VAL_DADO_ORIG_LKP NOT LIKE '%90000' OR  CRE.VAL_DADO_ORIG_LKP NOT LIKE '%08500')
AND COD_ORG_CTAF IN (373,353,372,352,375,355,374,354,377,357,360,362,365,367)
AND DAT_TRANS_SAQ >= '2023-01-01' --AND '2022-12-31' 	----  PERIODO DE DISPOSICIONES
AND CUENTAREAL IS NOT NULL
) AS A