WITH PeriodoActual AS (
    SELECT 
        DATEADD(WEEK, DATEDIFF(WEEK, 0, FECHA_CONSUMO), 0) AS Fecha_Agrupada,
        LEFT(NUM_CUENTA, 6) AS BINES,
        CASE 
            WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 1 THEN 'DOMINGO'
            WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 2 THEN 'LUNES'
            WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 3 THEN 'MARTES'
            WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 4 THEN 'MIERCOLES'
            WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 5 THEN 'JUEVES'
            WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 6 THEN 'VIERNES'
            WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 7 THEN 'SABADO'
        END AS DIA_NUMERO,
        COUNT(*) AS Total_Transacciones,
        COUNT(DISTINCT NUM_CUENTA) AS Total_Cuentas_Unicas,
        SUM(IMP_DESTINO) AS Suma_Importes
    FROM PROSA_510
    WHERE 
        FECHA_CONSUMO >= '2023-01-01 00:00:00.000' AND 
        FECHA_CONSUMO <= '2023-09-26 00:00:00.000' AND
		MCC_GIRO_COMERCIO = '07832' AND 
        TIPO_TRANSACCION = '01' AND 
        LEFT(NUM_CUENTA, 6) IN ('481284', '481281', '403750', '464811', '481282', '446351', '469849', '481283')
    GROUP BY DATEADD(WEEK, DATEDIFF(WEEK, 0, FECHA_CONSUMO), 0), LEFT(NUM_CUENTA, 6),
             CASE 
                WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 1 THEN 'DOMINGO'
                WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 2 THEN 'LUNES'
                WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 3 THEN 'MARTES'
                WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 4 THEN 'MIERCOLES'
                WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 5 THEN 'JUEVES'
                WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 6 THEN 'VIERNES'
                WHEN DATEPART(WEEKDAY, FECHA_CONSUMO) = 7 THEN 'SABADO'
            END
)
SELECT
    Fecha_Agrupada,
    BINES,
    DIA_NUMERO,
    COUNT(DISTINCT BINES) AS Cuentas_Unicas_Periodo,
    SUM(Suma_Importes) AS Suma_Importes_Periodo
FROM PeriodoActual
WHERE DIA_NUMERO IN ('JUEVES','VIERNES', 'SABADO', 'DOMINGO') -- Solo días VIERNES, SÁBADO y DOMINGO
GROUP BY Fecha_Agrupada, BINES, DIA_NUMERO
ORDER BY Fecha_Agrupada;