SELECT
    YEAR(ULTC) AS Anio,
    CASE
        WHEN ULTC IS NULL THEN 'NUNCA ACTIVO'
        WHEN ULTC >= DATEADD(DAY, -30, GETDATE()) THEN 'ACTIVE'
        WHEN ULTC BETWEEN DATEADD(DAY, -365, GETDATE()) AND DATEADD(DAY, -31, GETDATE()) THEN 'INACTIVE'
        ELSE 'CUENTAS DORMIDAS'
    END AS TIPO,
    COUNT(DISTINCT CUENTA) AS CuentasUnicas,
    SUM(1) AS TotalCuentas,
    SUM(CASE WHEN Bloq_Cobr = 'G' THEN 1 ELSE 0 END) AS CobroPreventivo,
    SUM(CASE WHEN Bloq_Cobr = 'N' THEN 1 ELSE 0 END) AS AcuerdoPagoInicial,
    SUM(CASE WHEN Bloq_Cobr = 'U' THEN 1 ELSE 0 END) AS Atraso120a179Dias,
    SUM(CASE WHEN Bloq_Cobr = 'W' THEN 1 ELSE 0 END) AS Atraso1a8Dias,
    SUM(CASE WHEN Bloq_Cobr = 'X' THEN 1 ELSE 0 END) AS Atraso9a59Dias,
    SUM(CASE WHEN Bloq_Cobr = 'Y' THEN 1 ELSE 0 END) AS Atraso60a119Dias,
    SUM(CASE WHEN Bloq_Cobr = 'Z' THEN 1 ELSE 0 END) AS AcuerdoPendienteSinPago,
    SUM(CASE WHEN Bloq_Cobr = '' THEN 1 ELSE 0 END) AS BloqueoVacio
FROM
    IT_CARTERA_PLCC_EXT
WHERE
    LEFT(REPLACE(SUBSTRING(CUENTA, 4, LEN(CUENTA)), '000', ''), 6) IN ('286900', '506329')
    AND (ULTC IS NULL OR ULTC >= DATEADD(DAY, -365, GETDATE()))
GROUP BY
    YEAR(ULTC),
    CASE
        WHEN ULTC IS NULL THEN 'NUNCA ACTIVO'
        WHEN ULTC >= DATEADD(DAY, -30, GETDATE()) THEN 'ACTIVE'
        WHEN ULTC BETWEEN DATEADD(DAY, -365, GETDATE()) AND DATEADD(DAY, -31, GETDATE()) THEN 'INACTIVE'
        ELSE 'CUENTAS DORMIDAS'
    END
ORDER BY
    YEAR(ULTC),
    CASE
        WHEN ULTC IS NULL THEN 'NUNCA ACTIVO'
        WHEN ULTC >= DATEADD(DAY, -30, GETDATE()) THEN 'ACTIVE'
        WHEN ULTC BETWEEN DATEADD(DAY, -365, GETDATE()) AND DATEADD(DAY, -31, GETDATE()) THEN 'INACTIVE'
        ELSE 'CUENTAS DORMIDAS'
    END;
